-- File này chứa lệnh tự động thêm các Brand nếu chưa tồn tại trong CSDL

INSERT INTO public.brands (name, slug) VALUES ('A Dimension', 'a-dimension') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('All For Play', 'all-for-play') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Alter', 'alter') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Amakuni', 'amakuni') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Amiami', 'amiami') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Amiami X Snail Shell', 'amiami-x-snail-shell') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Amie X Altair', 'amie-x-altair') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Anigift', 'anigift') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Animester', 'animester') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Aniplex', 'aniplex') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Apex', 'apex') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Apex Innovation', 'apex-innovation') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Axgrit', 'axgrit') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('B Full', 'b-full') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bandai', 'bandai') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bandai Namco Nui', 'bandai-namco-nui') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bandai Spirits', 'bandai-spirits') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Banpresto', 'banpresto') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bebox', 'bebox') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bilibili', 'bilibili') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Blackray', 'blackray') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Blokees', 'blokees') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Broccoli', 'broccoli') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bushiroad Creative', 'bushiroad-creative') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Bushiroad Inc', 'bushiroad-inc') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Cardfun', 'cardfun') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Cerberus Project', 'cerberus-project') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Claynel', 'claynel') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Cover Corp', 'cover-corp') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Cover Corporation', 'cover-corporation') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Design Coco', 'design-coco') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Designcoco', 'designcoco') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Dmm Factory', 'dmm-factory') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Dmm Make', 'dmm-make') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Eaki', 'eaki') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Elcoco', 'elcoco') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Elegant', 'elegant') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Ensky', 'ensky') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Estream', 'estream') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Firm 369', 'firm-369') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Flare', 'flare') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Freeing', 'freeing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Fukuya', 'fukuya') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Furyu', 'furyu') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Gemblo', 'gemblo') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Gift', 'gift') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Gnftoyz', 'gnftoyz') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Goldenhead', 'goldenhead') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Gong', 'gong') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Good Smile Arts Shanghai', 'good-smile-arts-shanghai') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Good Smile Company', 'good-smile-company') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Good Smile Racing', 'good-smile-racing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Hanabee', 'hanabee') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Heartsum', 'heartsum') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Hobby Max', 'hobby-max') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Hobby Sakura', 'hobby-sakura') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Hobby Stock', 'hobby-stock') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Hololive Official', 'hololive-official') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Idelite Figure', 'idelite-figure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kadokawa', 'kadokawa') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kaitendo', 'kaitendo') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kaiyodo', 'kaiyodo') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kayou', 'kayou') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kodansha', 'kodansha') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Konami Amusemen', 'konami-amusemen') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Konami Amusement', 'konami-amusement') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Konami Arcade Games', 'konami-arcade-games') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kotobukiya', 'kotobukiya') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Kt Model', 'kt-model') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Ldcx', 'ldcx') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Ldcx Lab', 'ldcx-lab') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Luminous Box', 'luminous-box') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('M Figure', 'm-figure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Max Factory', 'max-factory') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Max Limited', 'max-limited') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Medicos Entertainment', 'medicos-entertainment') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Megahouse', 'megahouse') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Mi Yin Studio', 'mi-yin-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Mimeyoi', 'mimeyoi') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Minidoll', 'minidoll') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Miyuki', 'miyuki') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Mocking Studio', 'mocking-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Moeyu', 'moeyu') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Moku Studio', 'moku-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Movic', 'movic') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Neonmax', 'neonmax') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Nic', 'nic') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Nullset', 'nullset') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Orange Rouge', 'orange-rouge') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Oriental Forest', 'oriental-forest') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Our Treasure', 'our-treasure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Phat Company', 'phat-company') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Piapro', 'piapro') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Plum', 'plum') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Pony Canyon', 'pony-canyon') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Prime 1 Studio', 'prime-1-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Proof', 'proof') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Puyoodoll', 'puyoodoll') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Qing Cang Studio', 'qing-cang-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Ques Q', 'ques-q') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Reverse Studio', 'reverse-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Ribose', 'ribose') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Sega', 'sega') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Shibuya Scramble Figure', 'shibuya-scramble-figure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Shonen Jump', 'shonen-jump') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Sk Japan', 'sk-japan') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Snail Shell', 'snail-shell') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Solarain', 'solarain') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Spiritale', 'spiritale') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Stargazer', 'stargazer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Stronger', 'stronger') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('System Service', 'system-service') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Taito', 'taito') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Takara Tomy', 'takara-tomy') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Thousand', 'thousand') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Trieagles Studio', 'trieagles-studio') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Union Creative', 'union-creative') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Wanderer', 'wanderer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Weiss Schwarz', 'weiss-schwarz') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Wing', 'wing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Wonderful Works', 'wonderful-works') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Yostar', 'yostar') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.brands (name, slug) VALUES ('Yowu', 'yowu') ON CONFLICT (slug) DO NOTHING;
